name: Infracost CI/CD

on:
  pull_request:
    paths:
      - '**/*.tf'
      - '**/*.tfvars'
  push:
    branches:
      - main

jobs:
  infracost:
    name: Infracost Breakdown
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.6.6

      - name: Setup Infracost
        uses: infracost/actions/setup@v2
        with:
          api-key: ${{ secrets.INFRACOST_API_KEY }}

      - name: Generate Infracost diff
        run: |
          infracost breakdown \
            --path=. \
            --format=json \
            --out-file=/tmp/infracost.json

      - name: Post Infracost comment to PR
        uses: infracost/actions/comment@v2
        with:
          path: /tmp/infracost.json
          behavior: update
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
