name: Infracost CI/CD

on:
  pull_request:
    paths:
      - '**/*.tf'
      - '**/*.tfvars'
      - '**/*.yml'
      - '**/*.yaml'
  push:
    branches: [main]

jobs:
  infracost:
    name: Infracost Breakdown
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.6.6

      - name: Cache Terraform providers
        uses: actions/cache@v3
        with:
          path: |
            ~/.terraform.d/plugin-cache
          key: ${{ runner.os }}-terraform-${{ hashFiles('**/*.tf') }}
          restore-keys: |
            ${{ runner.os }}-terraform-

      - name: Setup Infracost
        uses: infracost/actions/setup@v2
        with:
          api-key: ${{ secrets.INFRACOST_API_KEY }}

      - name: Run infracost breakdown
        run: |
          infracost breakdown \
            --path=. \
            --format=json \
            --out-file=/tmp/infracost.json

      - name: Post cost estimate to PR
        uses: infracost/actions/comment@v2
        with:
          path: /tmp/infracost.json
          behavior: update
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
